<script setup lang="ts">
const company = 'Pointhub'
const website = 'https://www.pointhub.net'
</script>

<template>
  <div class="flex flex-col h-full gap-16">
    <div class="bg-header">
      <div class="container mx-auto pt-[80px] h-60 lg:h-100">
        <div class="flex items-center justify-center text-white">
          <div class="flex-1 flex flex-col gap-4 justify-center">
            <h1 class="text-3xl lg:text-5xl font-extrabold">Privacy Policy</h1>
            <p>
              When you use our services, you’re trusting us with your information. We understand this is a big
              responsibility and work hard to protect your information and put you in control.
            </p>
          </div>
          <div class="flex-1 lg:flex items-center justify-center hidden">
            <img class="h-80" src="@/assets/images/policies/illustration-terms.png" />
          </div>
        </div>
      </div>
    </div>
    <div class="h-full flex p-4 gap-16 container mx-auto">
      <div class="hidden lg:block">
        <PoliciesSidebarMenu></PoliciesSidebarMenu>
      </div>
      <div class="prose max-w-screen-lg">
        <h1>Privacy Policy</h1>
        <div class="">
          <section>
            <h2 class="font-semibold">1. Introduction</h2>
            <p>
              By accessing the website at {{ website }}, you are agreeing to be bound by these terms of service, all
              applicable laws and regulations, and agree that you are responsible for compliance with any applicable
              local laws. If you do not agree with any of these terms, you are prohibited from using or accessing this
              site. The materials contained in this website are protected by applicable copyright and trademark law.
            </p>
          </section>
          <section>
            <h2 class="font-semibold">2. Definitions</h2>
            <p>For the purposes of this Privacy Policy:</p>
            <p><b>Account</b> means a unique account created for You to access our Service or parts of our Service.</p>
            <p>
              <b>Company</b> (referred to as either "the Company", "We", "Us" or "Our" in this Agreement) refers to PT
              Bumi Inovasi Ganapatih, Indonesia.
            </p>
            <p>
              <b>Cookies</b> are small files that are placed on Your computer, mobile device or any other device by a
              website, containing the details of Your browsing history on that website among its many uses.
            </p>
            <p>
              <b>Device</b> means any device that can access the Service such as a computer, a cellphone or a digital
              tablet.
            </p>
            <p><b>Personal Data</b> is any information that relates to an identified or identifiable individual.</p>
            <p><b>Service</b> refers to the Website.</p>
            <p>
              <b>Third-party Social Media Service</b> refers to any website or any social network website through which
              a User can log in or create an account to use the Service.
            </p>
            <p>
              <b>Usage data</b> refers to data collected automatically, either generated by the use of the Service or
              from the Service infrastructure itself (for example, the duration of a page visit).
            </p>
            <p><b>Website</b> refers to {{ company }} website, accessible from {{ website }}</p>
            <p>
              <b>You</b> means the individual accessing or using the Service, or the company, or other legal entity on
              behalf of which such individual is accessing or using the Service, as applicable.
            </p>
          </section>
          <section>
            <h2 class="font-semibold">3. Collecting and Using Your Personal Data</h2>
            <div>
              <h3>Personal Data</h3>
              <p>
                While using Our Service, We may ask You to provide Us with certain personally identifiable information
                that can be used to contact or identify You. Personally identifiable information may include, but is not
                limited to: (Name, Email address, Usage data)
              </p>
            </div>
            <div>
              <h3>Usage Data</h3>
              <p>Usage Data is collected automatically when using the Service.</p>
              <p>
                Usage Data may include information such as Your Device's Internet Protocol address (e.g. IP address),
                browser type, browser version, the pages of our Service that You visit, the time and date of Your visit,
                the time spent on those pages, unique device identifiers and other diagnostic data.
              </p>
              <p>
                When You access the Service by or through a mobile device, We may collect certain information
                automatically, including, but not limited to, the type of mobile device You use, Your mobile device
                unique ID, the IP address of Your mobile device, Your mobile operating system, the type of mobile
                Internet browser You use, unique device identifiers and other diagnostic data.
              </p>
              <p>
                We may also collect information that Your browser sends whenever You visit our Service or when You
                access the Service by or through a mobile device.
              </p>
            </div>
            <div>
              <h3>Information from Third-Party Social Media Services</h3>
              <p>
                The Company allows You to create an account and log in to use the Service through the Third-party Social
                Media Services "Google"
              </p>
              <p>
                If You decide to register through or otherwise grant us access to a Third-Party Social Media Service, We
                may collect Personal data that is already associated with Your Third-Party Social Media Service's
                account such as Your name, Your email address for help you Login faster in Our app. And We use your
                Google Drive account to store Your uploaded photo, so You will responsible with Your photos because We
                don't store in our storage
              </p>
            </div>
            <div>
              <h3>Tracking Technologies and Cookies</h3>
              <p>
                We use Cookies and similar tracking technologies to track the activity on Our Service and store certain
                information. Tracking technologies used are beacons, tags, and scripts to collect and track information
                and to improve and analyze Our Service. The technologies We use may include:
              </p>
              <p>
                <b>Cookies or Browser Cookies.</b> A cookie is a small file placed on Your Device. You can instruct Your
                browser to refuse all Cookies or to indicate when a Cookie is being sent. However, if You do not accept
                Cookies, You may not be able to use some parts of our Service. Unless you have adjusted Your browser
                setting so that it will refuse Cookies, our Service may use Cookies.
              </p>
              <p>
                Cookies can be "Persistent" or "Session" Cookies. Persistent Cookies remain on Your personal computer or
                mobile device when You go offline, while Session Cookies are deleted as soon as You close Your web
                browser. Learn more about cookies on the Privacy Policies website article.
              </p>
              <p>We use both Session and Persistent Cookies for the purposes set out below:</p>
              <div>
                <p><b>Necessary / Essential Cookies</b></p>
                <p>Type: Session Cookies</p>
                <p>Administered by: Us</p>
                <p>
                  Purpose: These Cookies are essential to provide You with services available through the Website and to
                  enable You to use some of its features. They help to authenticate users and prevent fraudulent use of
                  user accounts. Without these Cookies, the services that You have asked for cannot be provided, and We
                  only use these Cookies to provide You with those services.
                </p>
              </div>
              <div>
                <p><b>Cookies Policy / Notice Acceptance Cookies</b></p>
                <p>Type: Persistent Cookies</p>
                <p>Administered by: Us</p>
                <p>Purpose: These Cookies identify if users have accepted the use of cookies on the Website.</p>
              </div>
              <div>
                <p><b>Functionality Cookies</b></p>
                <p>Type: Persistent Cookies</p>
                <p>Administered by: Us</p>
                <p>
                  Purpose: These Cookies allow us to remember choices You make when You use the Website, such as
                  remembering your login details or language preference. The purpose of these Cookies is to provide You
                  with a more personal experience and to avoid You having to re-enter your preferences every time You
                  use the Website.
                </p>
              </div>
            </div>
          </section>
          <section>
            <h2 class="font-semibold">4. Use of Your Personal Data</h2>
            <p>The Company may use Personal Data for the following purposes:</p>
            <p><b>To provide and maintain our Service</b>, including to monitor the usage of our Service.</p>
            <p>
              <b>To manage Your Account:</b> to manage Your registration as a user of the Service. The Personal Data You
              provide can give You access to different functionalities of the Service that are available to You as a
              registered user.
            </p>
            <p>
              <b>For the performance of a contract:</b> the development, compliance and undertaking of the purchase
              contract for the products, items or services You have purchased or of any other contract with Us through
              the Service.
            </p>
            <p>
              <b>To contact You:</b> To contact You by email, telephone calls, SMS, or other equivalent forms of
              electronic communication, such as a mobile application's push notifications regarding updates or
              informative communications related to the functionalities, products or contracted services, including the
              security updates, when necessary or reasonable for their implementation.
            </p>
            <p>
              <b>To provide You with news</b>, special offers and general information about other goods, services and
              events which we offer that are similar to those that you have already purchased or enquired about unless
              You have opted not to receive such information.
            </p>
            <p><b>To manage Your requests:</b> To attend and manage Your requests to Us.</p>
            <p>
              <b>For business transfers:</b> We may use Your information to evaluate or conduct a merger, divestiture,
              restructuring, reorganization, dissolution, or other sale or transfer of some or all of Our assets,
              whether as a going concern or as part of bankruptcy, liquidation, or similar proceeding, in which Personal
              Data held by Us about our Service users is among the assets transferred.
            </p>
            <p>
              <b>For other purposes:</b> We may use Your information for other purposes, such as data analysis,
              identifying usage trends, determining the effectiveness of our promotional campaigns and to evaluate and
              improve our Service, products, services, marketing and your experience.
            </p>
          </section>
          <section>
            <h2 class="font-semibold">5. Security of Your Personal Data</h2>
            <p>
              The security of Your Personal Data is important to Us, but remember that no method of transmission over
              the Internet, or method of electronic storage is 100% secure. While We strive to use commercially
              acceptable means to protect Your Personal Data, We cannot guarantee its absolute security.
            </p>
          </section>
          <section>
            <h2 class="font-semibold">6. Links to Other Websites</h2>
            <p>
              Our Service may contain links to other websites that are not operated by Us. If You click on a third party
              link, You will be directed to that third party's site. We strongly advise You to review the Privacy Policy
              of every site You visit.
            </p>
            <p>
              We have no control over and assume no responsibility for the content, privacy policies or practices of any
              third party sites or services.
            </p>
          </section>
          <section>
            <h2 class="font-semibold">7. Changes to this Privacy Policy</h2>
            <p>
              We may update Our Privacy Policy from time to time. We will notify You of any changes by posting the new
              Privacy Policy on this page.
            </p>
            <p>
              We will let You know via email and/or a prominent notice on Our Service, prior to the change becoming
              effective and update the "Last updated" date at the top of this Privacy Policy.
            </p>
            <p>
              You are advised to review this Privacy Policy periodically for any changes. Changes to this Privacy Policy
              are effective when they are posted on this page.
            </p>
          </section>
          <section>
            <h2 class="font-semibold">8. Contact Us</h2>
            <p>If you have any questions about this Privacy Policy, You can contact us:</p>
            <p>By email: support@pointhub.net</p>
          </section>
        </div>
      </div>
    </div>
  </div>
</template>

<style scoped>
.bg-header {
  background-image: url('@/assets/images/banner-background.jpg');
  background-repeat: no-repeat;
  background-position: center bottom;
  @apply p-4;
}
</style>
